// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Lots.Data.Migrations
{
    [DbContext(typeof(LotsDbContext))]
    [Migration("20260711145053_AddAlfalotLotLinks")]
    partial class AddAlfalotLotLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("lots_public_id_seq")
                .StartsAt(10001L);

            modelBuilder.Entity("Lots.Data.Entities.AlfalotLotLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApplicationsEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LotNumberNormalized")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LotUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Status")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TradeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TradeNumberNormalized")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TradeUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_AlfalotLotLinks_UpdatedAt");

                    b.HasIndex("TradeNumberNormalized", "LotNumberNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_AlfalotLotLinks_TradeLotNormalized");

                    b.ToTable("AlfalotLotLinks");
                });

            modelBuilder.Entity("Lots.Data.Entities.Bidding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnnouncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArbitrationManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankruptMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("BidAcceptancePeriod")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DebtorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EnrichedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasNoLots")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsEnriched")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTradeStatusesFinalized")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastStatusCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LegalCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextStatusCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organizer")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResultsAnnouncementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusCheckAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("TradeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradePeriod")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViewingProcedure")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArbitrationManagerId");

                    b.HasIndex("DebtorId");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("Biddings");
                });

            modelBuilder.Entity("Lots.Data.Entities.BiddingScheduleUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BiddingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsExported")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextStatusCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusCheckAttempts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BiddingScheduleUpdates");
                });

            modelBuilder.Entity("Lots.Data.Entities.CadastralInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<double?>("Area")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("CadastralCost")
                        .HasColumnType("numeric");

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectType")
                        .HasColumnType("text");

                    b.Property<string>("OwnershipType")
                        .HasColumnType("text");

                    b.Property<string>("PermittedUse")
                        .HasColumnType("text");

                    b.Property<string>("RawGeoJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RegDate")
                        .HasColumnType("text");

                    b.Property<string>("RightType")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("CadastralInfo");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtCourtDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("LotDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<double?>("OcrConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("OcrText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("LotDocumentId");

                    b.HasIndex("LotId", "SourceUrl")
                        .HasDatabaseName("IX_DebtCourtDocuments_LotId_SourceUrl");

                    b.ToTable("DebtCourtDocuments");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtExtractedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CourtDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CourtDocumentId");

                    b.HasIndex("LotId", "EntityType")
                        .HasDatabaseName("IX_DebtExtractedEntities_LotId_EntityType");

                    b.ToTable("DebtExtractedEntities");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtLotProfile", b =>
                {
                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CaseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DebtBasis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("DebtNominal")
                        .HasColumnType("numeric");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LotId");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_DebtLotProfiles_EnrichmentQueue")
                        .HasFilter("\"Status\" IN (2, 3, 6)");

                    b.ToTable("DebtLotProfiles");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorBankruptcyCheck", b =>
                {
                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankruptcyCaseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInBankruptcy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStopFactor")
                        .HasColumnType("boolean");

                    b.Property<string>("RawResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("StatusText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("LotId");

                    b.ToTable("DebtorBankruptcyChecks");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorEnrichmentProfile", b =>
                {
                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<int>("BankruptcyStepStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DebtorType")
                        .HasColumnType("integer");

                    b.Property<int>("FnsStepStatus")
                        .HasColumnType("integer");

                    b.Property<int>("FsspStepStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsResolvedInnEncrypted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolvedNameEncrypted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolvedSnilsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<int>("KadStepStatus")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedInn")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ResolvedName")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ResolvedSnils")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LotId");

                    b.HasIndex("SubjectId");

                    b.ToTable("DebtorEnrichmentProfiles");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorFnsSnapshot", b =>
                {
                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompanyStatus")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyStatusText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStopFactor")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NetAssets")
                        .HasColumnType("numeric");

                    b.Property<string>("RawResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric");

                    b.HasKey("LotId");

                    b.ToTable("DebtorFnsSnapshots");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorFsspRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ClosedUnderArticle46")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("DebtAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStopFactor")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProceedingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LotId")
                        .HasDatabaseName("IX_DebtorFsspRecords_LotId");

                    b.ToTable("DebtorFsspRecords");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorKadCaseSnapshot", b =>
                {
                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CaseSubject")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CourtName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisputeCategory")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DocumentsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastActDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("LotId");

                    b.ToTable("DebtorKadCaseSnapshots");
                });

            modelBuilder.Entity("Lots.Data.Entities.DeepSeekBudgetState", b =>
                {
                    b.Property<string>("PeriodKey")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TokenCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PeriodKey");

                    b.ToTable("DeepSeekBudgetStates");
                });

            modelBuilder.Entity("Lots.Data.Entities.DeepSeekCircuitBreaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("OpenUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DeepSeekCircuitBreakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UpdatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Lots.Data.Entities.EnrichmentState", b =>
                {
                    b.Property<Guid>("BiddingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("MissingImagesAttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("BiddingId");

                    b.ToTable("EnrichmentStates");
                });

            modelBuilder.Entity("Lots.Data.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Lots.Data.Entities.LegalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("LegalCases");
                });

            modelBuilder.Entity("Lots.Data.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("BiddingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("InvestmentSummary")
                        .HasColumnType("text");

                    b.Property<bool>("IsSharedOwnership")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarketValueMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarketValueMin")
                        .HasColumnType("numeric");

                    b.Property<bool>("NeedsDescriptionReview")
                        .HasColumnType("boolean");

                    b.Property<string>("PriceConfidence")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PropertyFullAddress")
                        .HasColumnType("text");

                    b.Property<string>("PropertyRegionCode")
                        .HasColumnType("text");

                    b.Property<string>("PropertyRegionName")
                        .HasColumnType("text");

                    b.Property<int>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('lots_public_id_seq')");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "russian_h")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "Description" });

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("StartPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Step")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TradeStatus")
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<string>("ViewingProcedure")
                        .HasColumnType("text");

                    b.Property<int>("VotesCount")
                        .HasColumnType("integer");

                    b.Property<string>("WinnerInn")
                        .HasColumnType("text");

                    b.Property<string>("WinnerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BiddingId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("TradeStatus")
                        .HasDatabaseName("IX_Lots_ActiveTradeStatus")
                        .HasFilter("\"TradeStatus\" IS NULL OR \"TradeStatus\" = '' OR \"TradeStatus\" NOT IN ('Завершенные', 'Торги отменены', 'Торги не состоялись', 'Торги завершены (нет данных)', 'Аннулированные')");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_Lots_Coordinates")
                        .HasFilter("\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BiddingType")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Categories")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryTimeStr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSharedOwnership")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<string[]>("RegionCodes")
                        .HasColumnType("text[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LotAlerts");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotAlertMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LotAlertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsSent")
                        .HasDatabaseName("IX_LotAlertMatches_Unsent")
                        .HasFilter("\"IsSent\" = FALSE");

                    b.HasIndex("LotAlertId");

                    b.HasIndex("LotId");

                    b.ToTable("LotAlertMatches");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LotId", "EventType")
                        .HasDatabaseName("IX_LotAuditEvents_LotId_EventType");

                    b.ToTable("LotAuditEvents");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotCadastralNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CleanCadastralNumber")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("regexp_replace(\"CadastralNumber\", '\\D', '', 'g')", true);

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CleanCadastralNumber");

                    b.HasIndex("LotId");

                    b.ToTable("LotCadastralNumbers");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("LotCategories");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotClassificationAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RawResponseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedCategories")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SuggestedCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("LotClassificationAnalysis");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotClassificationState", b =>
                {
                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("LotId");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_ClassificationStates_Queue")
                        .HasFilter("\"Status\" IN (0, 1, 3)");

                    b.ToTable("LotClassificationStates");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("InvestmentSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LiquidityScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ReasoningText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReasoningTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("LotEvaluations");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotEvaluationUserRunStatistics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LotEvaluationUserRunStatistics");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("LotImages");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotPriceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EstimatedRank")
                        .HasColumnType("double precision");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PotentialRoi")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("LotPriceSchedules");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotTradeResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BiddingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionJustification")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsExportedToProd")
                        .HasColumnType("boolean");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("WinnerInn")
                        .HasColumnType("text");

                    b.Property<string>("WinnerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BiddingId");

                    b.ToTable("LotTradeResults");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LotId", "UserId")
                        .IsUnique();

                    b.ToTable("LotVotes");
                });

            modelBuilder.Entity("Lots.Data.Entities.RawFedresursMessage", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePublish")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Guid");

                    b.ToTable("RawFedresursMessages");
                });

            modelBuilder.Entity("Lots.Data.Entities.SimilarLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .HasColumnType("text");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetLotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceLotId");

                    b.HasIndex("TargetLotId");

                    b.ToTable("SimilarLots");
                });

            modelBuilder.Entity("Lots.Data.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Inn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ogrn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Snils")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Lots.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubscriptionActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("UserAds");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAdChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAdChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAdImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAdId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAdId");

                    b.ToTable("UserAdImages");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserLotContractPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FixedRewardAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SuccessRewardAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("UserId", "LotId")
                        .IsUnique();

                    b.ToTable("UserLotContractPermissions");
                });

            modelBuilder.Entity("Lots.Data.Entities.Bidding", b =>
                {
                    b.HasOne("Lots.Data.Entities.Subject", "ArbitrationManager")
                        .WithMany()
                        .HasForeignKey("ArbitrationManagerId");

                    b.HasOne("Lots.Data.Entities.Subject", "Debtor")
                        .WithMany()
                        .HasForeignKey("DebtorId");

                    b.HasOne("Lots.Data.Entities.LegalCase", "LegalCase")
                        .WithMany()
                        .HasForeignKey("LegalCaseId");

                    b.Navigation("ArbitrationManager");

                    b.Navigation("Debtor");

                    b.Navigation("LegalCase");
                });

            modelBuilder.Entity("Lots.Data.Entities.CadastralInfo", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("CadastralInfos")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtCourtDocument", b =>
                {
                    b.HasOne("Lots.Data.Entities.LotDocument", "LotDocument")
                        .WithMany()
                        .HasForeignKey("LotDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lots.Data.Entities.DebtScoring.DebtLotProfile", "Profile")
                        .WithMany("CourtDocuments")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LotDocument");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtExtractedEntity", b =>
                {
                    b.HasOne("Lots.Data.Entities.DebtScoring.DebtCourtDocument", "CourtDocument")
                        .WithMany("ExtractedEntities")
                        .HasForeignKey("CourtDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lots.Data.Entities.DebtScoring.DebtLotProfile", "Profile")
                        .WithMany("ExtractedEntities")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourtDocument");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtLotProfile", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithOne()
                        .HasForeignKey("Lots.Data.Entities.DebtScoring.DebtLotProfile", "LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorBankruptcyCheck", b =>
                {
                    b.HasOne("Lots.Data.Entities.DebtScoring.DebtorEnrichmentProfile", "EnrichmentProfile")
                        .WithOne("BankruptcyCheck")
                        .HasForeignKey("Lots.Data.Entities.DebtScoring.DebtorBankruptcyCheck", "LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnrichmentProfile");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorEnrichmentProfile", b =>
                {
                    b.HasOne("Lots.Data.Entities.DebtScoring.DebtLotProfile", "DebtLotProfile")
                        .WithOne("EnrichmentProfile")
                        .HasForeignKey("Lots.Data.Entities.DebtScoring.DebtorEnrichmentProfile", "LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lots.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DebtLotProfile");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorFnsSnapshot", b =>
                {
                    b.HasOne("Lots.Data.Entities.DebtScoring.DebtorEnrichmentProfile", "EnrichmentProfile")
                        .WithOne("FnsSnapshot")
                        .HasForeignKey("Lots.Data.Entities.DebtScoring.DebtorFnsSnapshot", "LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnrichmentProfile");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorFsspRecord", b =>
                {
                    b.HasOne("Lots.Data.Entities.DebtScoring.DebtorEnrichmentProfile", "EnrichmentProfile")
                        .WithMany("FsspRecords")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnrichmentProfile");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorKadCaseSnapshot", b =>
                {
                    b.HasOne("Lots.Data.Entities.DebtScoring.DebtorEnrichmentProfile", "EnrichmentProfile")
                        .WithOne("KadCaseSnapshot")
                        .HasForeignKey("Lots.Data.Entities.DebtScoring.DebtorKadCaseSnapshot", "LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnrichmentProfile");
                });

            modelBuilder.Entity("Lots.Data.Entities.EnrichmentState", b =>
                {
                    b.HasOne("Lots.Data.Entities.Bidding", "Bidding")
                        .WithOne("EnrichmentState")
                        .HasForeignKey("Lots.Data.Entities.EnrichmentState", "BiddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bidding");
                });

            modelBuilder.Entity("Lots.Data.Entities.Lot", b =>
                {
                    b.HasOne("Lots.Data.Entities.Bidding", "Bidding")
                        .WithMany("Lots")
                        .HasForeignKey("BiddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bidding");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotAlert", b =>
                {
                    b.HasOne("Lots.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotAlertMatch", b =>
                {
                    b.HasOne("Lots.Data.Entities.LotAlert", "LotAlert")
                        .WithMany()
                        .HasForeignKey("LotAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");

                    b.Navigation("LotAlert");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotCadastralNumber", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("CadastralNumbers")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotCategory", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("Categories")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotClassificationState", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithOne()
                        .HasForeignKey("Lots.Data.Entities.LotClassificationState", "LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotDocument", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("Documents")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotEvaluation", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotImage", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("Images")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotPriceSchedule", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("PriceSchedules")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotTradeResult", b =>
                {
                    b.HasOne("Lots.Data.Entities.Bidding", "Bidding")
                        .WithMany()
                        .HasForeignKey("BiddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bidding");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotVote", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.SimilarLot", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "TargetLot")
                        .WithMany()
                        .HasForeignKey("TargetLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetLot");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAd", b =>
                {
                    b.HasOne("Lots.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAdChatMessage", b =>
                {
                    b.HasOne("Lots.Data.Entities.UserAdChatRoom", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAdChatRoom", b =>
                {
                    b.HasOne("Lots.Data.Entities.UserAd", "Ad")
                        .WithMany()
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAdImage", b =>
                {
                    b.HasOne("Lots.Data.Entities.UserAd", "UserAd")
                        .WithMany("Images")
                        .HasForeignKey("UserAdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAd");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserLotContractPermission", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lots.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lots.Data.Entities.Bidding", b =>
                {
                    b.Navigation("EnrichmentState");

                    b.Navigation("Lots");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtCourtDocument", b =>
                {
                    b.Navigation("ExtractedEntities");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtLotProfile", b =>
                {
                    b.Navigation("CourtDocuments");

                    b.Navigation("EnrichmentProfile");

                    b.Navigation("ExtractedEntities");
                });

            modelBuilder.Entity("Lots.Data.Entities.DebtScoring.DebtorEnrichmentProfile", b =>
                {
                    b.Navigation("BankruptcyCheck");

                    b.Navigation("FnsSnapshot");

                    b.Navigation("FsspRecords");

                    b.Navigation("KadCaseSnapshot");
                });

            modelBuilder.Entity("Lots.Data.Entities.Lot", b =>
                {
                    b.Navigation("CadastralInfos");

                    b.Navigation("CadastralNumbers");

                    b.Navigation("Categories");

                    b.Navigation("Documents");

                    b.Navigation("Images");

                    b.Navigation("PriceSchedules");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAd", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Lots.Data.Entities.UserAdChatRoom", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
