// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Lots.Data.Migrations
{
    [DbContext(typeof(LotsDbContext))]
    [Migration("20260224100606_AddActiveLotPartialIndex")]
    partial class AddActiveLotPartialIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("lots_public_id_seq")
                .StartsAt(10001L);

            modelBuilder.Entity("Lots.Data.Entities.Bidding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnnouncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArbitrationManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankruptMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("BidAcceptancePeriod")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DebtorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EnrichedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsEnriched")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTradeStatusesFinalized")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastStatusCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LegalCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextStatusCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organizer")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResultsAnnouncementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TradeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradePeriod")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViewingProcedure")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArbitrationManagerId");

                    b.HasIndex("DebtorId");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("Biddings");
                });

            modelBuilder.Entity("Lots.Data.Entities.EnrichmentState", b =>
                {
                    b.Property<Guid>("BiddingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("MissingImagesAttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("BiddingId");

                    b.ToTable("EnrichmentStates");
                });

            modelBuilder.Entity("Lots.Data.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Lots.Data.Entities.LegalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("LegalCases");
                });

            modelBuilder.Entity("Lots.Data.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BiddingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("InvestmentSummary")
                        .HasColumnType("text");

                    b.Property<bool>("IsSharedOwnership")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarketValueMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarketValueMin")
                        .HasColumnType("numeric");

                    b.Property<string>("PriceConfidence")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PropertyFullAddress")
                        .HasColumnType("text");

                    b.Property<string>("PropertyRegionCode")
                        .HasColumnType("text");

                    b.Property<string>("PropertyRegionName")
                        .HasColumnType("text");

                    b.Property<int>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('lots_public_id_seq')");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "russian_h")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "Description" });

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("StartPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Step")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TradeStatus")
                        .HasColumnType("text");

                    b.Property<string>("ViewingProcedure")
                        .HasColumnType("text");

                    b.Property<string>("WinnerInn")
                        .HasColumnType("text");

                    b.Property<string>("WinnerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BiddingId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("TradeStatus")
                        .HasDatabaseName("IX_Lots_ActiveTradeStatus")
                        .HasFilter("\"TradeStatus\" IS NULL OR \"TradeStatus\" = '' OR \"TradeStatus\" NOT IN ('Завершенные', 'Торги отменены', 'Торги не состоялись', 'Торги завершены (нет данных)')");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LotId", "EventType")
                        .HasDatabaseName("IX_LotAuditEvents_LotId_EventType");

                    b.ToTable("LotAuditEvents");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotCadastralNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CleanCadastralNumber")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("regexp_replace(\"CadastralNumber\", '\\D', '', 'g')", true);

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CleanCadastralNumber");

                    b.HasIndex("LotId");

                    b.ToTable("LotCadastralNumbers");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("LotCategories");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotClassificationAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RawResponseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedCategories")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SuggestedCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("LotClassificationAnalysis");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("InvestmentSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LiquidityScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ReasoningText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReasoningTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("LotEvaluations");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotEvaluationUserRunStatistics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LotEvaluationUserRunStatistics");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("LotImages");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotPriceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EstimatedRank")
                        .HasColumnType("double precision");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PotentialRoi")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("LotPriceSchedules");
                });

            modelBuilder.Entity("Lots.Data.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Inn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ogrn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Snils")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Lots.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSubscriptionActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Lots.Data.Entities.Bidding", b =>
                {
                    b.HasOne("Lots.Data.Entities.Subject", "ArbitrationManager")
                        .WithMany()
                        .HasForeignKey("ArbitrationManagerId");

                    b.HasOne("Lots.Data.Entities.Subject", "Debtor")
                        .WithMany()
                        .HasForeignKey("DebtorId");

                    b.HasOne("Lots.Data.Entities.LegalCase", "LegalCase")
                        .WithMany()
                        .HasForeignKey("LegalCaseId");

                    b.Navigation("ArbitrationManager");

                    b.Navigation("Debtor");

                    b.Navigation("LegalCase");
                });

            modelBuilder.Entity("Lots.Data.Entities.EnrichmentState", b =>
                {
                    b.HasOne("Lots.Data.Entities.Bidding", "Bidding")
                        .WithOne("EnrichmentState")
                        .HasForeignKey("Lots.Data.Entities.EnrichmentState", "BiddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bidding");
                });

            modelBuilder.Entity("Lots.Data.Entities.Lot", b =>
                {
                    b.HasOne("Lots.Data.Entities.Bidding", "Bidding")
                        .WithMany("Lots")
                        .HasForeignKey("BiddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bidding");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotCadastralNumber", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("CadastralNumbers")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotCategory", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("Categories")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotDocument", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("Documents")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotEvaluation", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotImage", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("Images")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.LotPriceSchedule", b =>
                {
                    b.HasOne("Lots.Data.Entities.Lot", "Lot")
                        .WithMany("PriceSchedules")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Lots.Data.Entities.Bidding", b =>
                {
                    b.Navigation("EnrichmentState");

                    b.Navigation("Lots");
                });

            modelBuilder.Entity("Lots.Data.Entities.Lot", b =>
                {
                    b.Navigation("CadastralNumbers");

                    b.Navigation("Categories");

                    b.Navigation("Documents");

                    b.Navigation("Images");

                    b.Navigation("PriceSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
